### ISSUE TITLE
GBv2 only works with google accounts with enabled "less secure apps" option.

### ISSUE THREAD

**Issue by Alvin-22** [DEMON1A/GmailBruterV2#7]
Doesn't work because it requires Gmail "less secure apps" enabled, should definitely include this note for the people thinking it will work or atleast a way to make it "secure"!

**Comment by DEMON1A** [comment]
Hey @Alvin-22, Thanks for your time creating this issue. But i already mentioned that the tool isn't working because of gmail second layer protection. see README before this edit: fd7710d. In fact, all gmail brute-force scrips isn't working. But i was able to limited the possible passwords from large lists into 3-6 passwords. gmail service auto close the connection with different SMTP error to stop the attacker from accessing the victim account when the valid account is found and there's a brute-force attack. i'm still working on an algorithm for that but i don't really have that much of time. i manage a lot of projects at the same time and updating it so i'm not really free right now.

But BTW, i will include that the tool isn't working on the current time until i decide to start working on it again. thanks for your help.

**Comment by DEMON1A** [comment]
I included documentations about this issue in the README: https://github.com/DEMON1A/GmailBruterV2/#when-gmailbruter-creates-a-successful-brute-force-attack. Thanks Alvin for all of your work.
